function addslashes(string) {
  return string.replace(/&acute;/g, "´")
               .replace(/&aacute;/g, 'á')
               .replace(/&eacute;/g, 'é')
               .replace(/&iacute;/g, 'í')
               .replace(/&oacute;/g, 'ó')
               .replace(/&uacute;/g, 'ú')
               .replace(/&Aacute;/g, 'Á')
               .replace(/&Eacute;/g, 'É')
               .replace(/&Iacute;/g, 'Í')
               .replace(/&Oacute;/g, 'Ó')
               .replace(/&Uacute;/g, 'Ú')
               .replace(/&uml;/g, '¨')
               .replace(/&auml;/g, 'ä')
               .replace(/&euml;/g, 'ë')
               .replace(/&iuml;/g, 'ï')
               .replace(/&ouml;/g, 'ö')
               .replace(/&uuml;/g, 'ü')
               .replace(/&Auml;/g, 'Ä')
               .replace(/&Euml;/g, 'Ë')
               .replace(/&Iuml;/g, 'Ï')
               .replace(/&Ouml;/g, 'Ö')
               .replace(/&Uuml;/g, 'Ü')
               .replace(/&ntilde;/g, 'ñ')
               .replace(/&Ntilde;/g, 'Ñ')
               .replace(/&quot;/g, '"')
               .replace(/&#39;/g, "'")
               .replace(/&not;/g, '¬')
               .replace(/&deg;/g, '°')
               .replace(/&iquest;/g, '¿')
               .replace(/&iexcl;/g, '¡')
               .replace(/&lt;/g, '<')
               .replace(/&gt;/g, '>')
               .replace(/&nbsp;/g, '  ')
               .replace(/&amp;/g, '&');
}
